# Generated by Django 2.1.2 on 2018-10-20 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome da disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome da prova')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina', to='questoes.Disciplina', verbose_name='disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
            ],
            options={
                'verbose_name': 'prova',
                'verbose_name_plural': 'provas',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('enunciado', models.TextField(verbose_name='enunciado')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem da questão')),
                ('alternativa_um', models.CharField(max_length=255, verbose_name='1ª alternativa')),
                ('alternativa_dois', models.CharField(max_length=255, verbose_name='2ª alternativa')),
                ('alternativa_tres', models.CharField(max_length=255, verbose_name='3ª alternativa')),
                ('alternativa_quatro', models.CharField(max_length=255, verbose_name='4ª alternativa')),
                ('correta', models.CharField(max_length=255, verbose_name='alternativa correta')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='questoes.Disciplina', verbose_name='disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL, verbose_name='professor')),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
            },
        ),
        migrations.AddField(
            model_name='prova',
            name='questoes',
            field=models.ManyToManyField(blank=True, related_name='questions', to='questoes.Questao', verbose_name='questões da prova'),
        ),
    ]
